import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile,writeFile,mkdir,mkdtemp,rm,chmod,readdir,lstat,symlink} from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';
import {createHash} from 'node:crypto';
import {validateRosterSnapshot,publishRosterRelease,prepareRosterRelease,listRosterReleases,loadRosterRelease,stageRosterRefresh} from '../src/rosterReleases.mjs';

// These publication scenarios deliberately use the original dated source fixture.
const dbBytes=await readFile(new URL('../public/data/database.json',import.meta.url)),hgBytes=await readFile(new URL('../public/data/releases/2026-10-03-initial/homegrown.json',import.meta.url));
const database=JSON.parse(dbBytes),homegrown=JSON.parse(hgBytes),hash=bytes=>createHash('sha256').update(bytes).digest('hex');
async function removeTree(dir){for(const item of await readdir(dir,{withFileTypes:true}).catch(()=>[]))if(item.isDirectory()){await chmod(path.join(dir,item.name),0o755);await removeTree(path.join(dir,item.name));}await rm(dir,{recursive:true,force:true});}
async function root(t){const dir=await mkdtemp(path.join(os.tmpdir(),'touchline-release-test-'));t.after(()=>removeTree(dir));await mkdir(path.join(dir,'public/data'),{recursive:true});await mkdir(path.join(dir,'saves'));await writeFile(path.join(dir,'public/data/database.json'),dbBytes);await writeFile(path.join(dir,'public/data/homegrown.json'),hgBytes);await writeFile(path.join(dir,'saves/existing-career.json'),'THIS FILE MUST NEVER CHANGE');return dir;}
const opts=rootDir=>({rootDir,id:'snapshot-20261003',name:'Đội hình 03/10/2026',season:'2026/27',asOf:'2026-10-03',publishedAt:'2026-10-03T12:00:00.000Z'});

test('updated training evidence validates at its own date and cannot be backdated into a historical release',async()=>{
 const latest=JSON.parse(await readFile(new URL('../public/data/homegrown.json',import.meta.url)));
 assert.equal(validateRosterSnapshot(database,latest,{season:'2026/27',asOf:'2026-10-05'}).homegrownPlayers,5192);
 assert.throws(()=>validateRosterSnapshot(database,latest,{asOf:'2026-10-03'}),/newer|after/);
 const record=Object.values(latest.players).find(p=>p.uefaSquads?.length),squad=record.uefaSquads[0];
 for(const change of [s=>s.list='X',s=>s.clubId='missing',s=>s.season='2027/28',s=>s.observedAt='2030-01-01',s=>s.source='https://example.org/unverified']){const old=structuredClone(squad);change(squad);assert.throws(()=>validateRosterSnapshot(database,latest,{asOf:'2026-10-05'}),/UEFA/);Object.assign(squad,old);}
});

test('current sourced snapshot validates; malformed identity, coverage, evidence or season cannot be overridden',()=>{
 assert.deepEqual(validateRosterSnapshot(database,homegrown,{season:'2026/27',asOf:'2026-10-03'}),{leagues:30,clubs:568,players:16440,homegrownPlayers:518});
 for(const change of [d=>d.players.push({...d.players[0]}),d=>d.players[0].clubId='missing',d=>d.players[0].position='invalid',d=>d.players[0].attributes={pace:20},d=>d.leagues[0].expectedTeams++,d=>d.competitions[0].participants[0]='missing',d=>d.players=d.players.slice(0,500)]){const d=structuredClone(database);change(d);assert.throws(()=>validateRosterSnapshot(d,homegrown));}
 const hg=structuredClone(homegrown);Object.values(hg.players)[0].name='Another person';assert.throws(()=>validateRosterSnapshot(database,hg));assert.throws(()=>validateRosterSnapshot(database,homegrown,{season:'2027/28'}));assert.throws(()=>validateRosterSnapshot(database,homegrown,{asOf:'2026-10-02'}));
});
test('publication preserves exact bytes, immutable version IDs and every existing save',async t=>{
 const rootDir=await root(t),settings=opts(rootDir),release=await publishRosterRelease(settings);assert.equal(release.asOf,'2026-10-03');assert.equal(release.publishedAt,'2026-10-03T12:00:00.000Z');assert.equal(release.label,release.name);assert.equal(release.hashes.database,hash(dbBytes));assert.equal(release.hashes.homegrown,hash(hgBytes));
 assert.equal((await readFile(path.join(rootDir,'saves/existing-career.json'))).toString(),'THIS FILE MUST NEVER CHANGE');assert.deepEqual(await readFile(path.join(rootDir,'public/data/database.json')),dbBytes);assert.deepEqual(await readFile(path.join(rootDir,'public/data/releases',release.id,'database.json')),dbBytes);
 const loaded=await loadRosterRelease(release.id,{rootDir});assert.deepEqual(loaded.database,database);assert.deepEqual(loaded.homegrown,homegrown);assert.deepEqual(await listRosterReleases({rootDir}),[release]);await assert.rejects(publishRosterRelease(settings),/cannot be overwritten/);assert.deepEqual(await listRosterReleases({rootDir}),[release]);assert.equal((await lstat(path.join(rootDir,'public/data/releases',release.id,'database.json'))).mode&0o222,0);
});
test('content tampering, traversal and corrupt manifest metadata are rejected during offline reads',async t=>{
 const rootDir=await root(t),release=await publishRosterRelease(opts(rootDir)),file=path.join(rootDir,'public/data/releases',release.id,'database.json');await chmod(file,0o600);await writeFile(file,Buffer.concat([dbBytes,Buffer.from(' ')]));await assert.rejects(loadRosterRelease(release.id,{rootDir}),/hash mismatch/);await assert.rejects(loadRosterRelease('../database',{rootDir}),/Invalid/);await assert.rejects(loadRosterRelease('missing',{rootDir}),e=>e.code==='ROSTER_RELEASE_NOT_FOUND');
 const indexFile=path.join(rootDir,'public/data/releases/index.json'),manifest=JSON.parse(await readFile(indexFile));manifest.releases[0].asOf='2026-10-02';await writeFile(indexFile,JSON.stringify(manifest));await assert.rejects(listRosterReleases({rootDir}),/checksum mismatch/);
});
test('publication lock prevents concurrent writers and leaves no partially listed release',async t=>{
 const rootDir=await root(t);await mkdir(path.join(rootDir,'public/data/releases'));const lock=path.join(rootDir,'public/data/releases/.publish.lock');await writeFile(lock,'active test publisher');await assert.rejects(publishRosterRelease(opts(rootDir)),e=>e.code==='ROSTER_RELEASE_LOCKED');assert.deepEqual(await listRosterReleases({rootDir}),[]);assert.equal(await readFile(lock,'utf8'),'active test publisher');await rm(lock);
 const results=await Promise.allSettled([publishRosterRelease(opts(rootDir)),publishRosterRelease({...opts(rootDir),id:'another'})]);assert.equal(results.filter(r=>r.status==='fulfilled').length,1);assert.equal((await listRosterReleases({rootDir})).length,1);
});
test('roster-loss review requires exact risk codes and a substantive explanation; validation failure changes no live files',async t=>{
 const rootDir=await root(t);await publishRosterRelease(opts(rootDir));const d=structuredClone(database),hg=structuredClone(homegrown),protectedIds=new Set(Object.keys(hg.players));
 // A credible-looking truncated scrape preserves minimum squads but loses more than 5% of players globally.
 const counts=new Map();for(const p of d.players)counts.set(p.clubId,(counts.get(p.clubId)||0)+1);let removed=0;d.players=d.players.filter(p=>{if(p.position!=='GK'&&!protectedIds.has(p.id)&&(counts.get(p.clubId)||0)>20&&removed<1100){counts.set(p.clubId,counts.get(p.clubId)-1);removed++;return false;}return true;});
 const candidate=path.join(rootDir,'candidate.json');await writeFile(candidate,JSON.stringify(d));const settings={...opts(rootDir),id:'reviewed-next',databasePath:candidate,publishedAt:'2026-10-04T12:00:00Z'};let risks;await assert.rejects(prepareRosterRelease(settings),e=>{risks=e.risks;return e.code==='ROSTER_REVIEW_REQUIRED';});assert.ok(risks.some(r=>r.code==='TOTAL_PLAYER_DROP'));await assert.rejects(publishRosterRelease({...settings,acknowledgeRisks:['*'],reviewNote:'Reviewed all source lists manually.'}),/exact current risk/);await assert.rejects(publishRosterRelease({...settings,acknowledgeRisks:risks.map(r=>r.code),reviewNote:'ok'}),/20–2,000/);assert.equal((await listRosterReleases({rootDir})).length,1);
 const approved=await publishRosterRelease({...settings,acknowledgeRisks:risks.map(r=>r.code),reviewNote:'Fixture deliberately removes 1,100 source players to test the explicit review path.'});assert.ok(approved.review.risks.length);assert.equal((await listRosterReleases({rootDir}))[0].id,'reviewed-next');assert.deepEqual(await readFile(path.join(rootDir,'public/data/database.json')),dbBytes);assert.equal(await readFile(path.join(rootDir,'saves/existing-career.json'),'utf8'),'THIS FILE MUST NEVER CHANGE');
});
test('dry-run validates without writing, sorts by source coverage before publication date, and rejects stale future-season adapters',async t=>{
 const rootDir=await root(t);const proposed=await prepareRosterRelease(opts(rootDir));assert.equal(proposed.release.id,'snapshot-20261003');assert.deepEqual(await listRosterReleases({rootDir}),[]);await publishRosterRelease(opts(rootDir));await publishRosterRelease({...opts(rootDir),id:'snapshot-20261004',asOf:'2026-10-04',publishedAt:'2026-10-04T12:00:00Z'});await publishRosterRelease({...opts(rootDir),id:'republished-old-coverage',publishedAt:'2026-10-05T12:00:00Z'});assert.deepEqual((await listRosterReleases({rootDir})).map(r=>r.id),['snapshot-20261004','republished-old-coverage','snapshot-20261003']);await assert.rejects(prepareRosterRelease({...opts(rootDir),id:'wrong-season',season:'2027/28'}),/source season/);await assert.rejects(prepareRosterRelease({...opts(rootDir),id:'future',asOf:'2099-10-03'}),/later than publication/);
});
test('staging isolates the existing Python refreshers, never copies saves, and refuses symlink routes into live data',async t=>{
 const rootDir=await root(t);await mkdir(path.join(rootDir,'scripts'));await writeFile(path.join(rootDir,'scripts/refresh-data.py'),'raise RuntimeError("simulated source failure")\n');await writeFile(path.join(rootDir,'scripts/refresh-homegrown.py'),'pass\n');const stage=path.join(rootDir,'work/stage');await stageRosterRefresh({rootDir,stageDir:stage});assert.equal(await readFile(path.join(stage,'public/data/database.json'),'utf8'),dbBytes.toString());await assert.rejects(lstat(path.join(stage,'saves')),e=>e.code==='ENOENT');await assert.rejects(stageRosterRefresh({rootDir,stageDir:stage}),/must be new/);await assert.rejects(stageRosterRefresh({rootDir,stageDir:path.join(rootDir,'public/stage')}),/live public/);await symlink(path.join(rootDir,'public'),path.join(rootDir,'shortcut'));await assert.rejects(stageRosterRefresh({rootDir,stageDir:path.join(rootDir,'shortcut/hidden-stage')}),/live public/);
 const failed=path.join(rootDir,'work/failed');await assert.rejects(stageRosterRefresh({rootDir,stageDir:failed,refresh:true}),/Staged refresh failed/);assert.equal(JSON.parse(await readFile(path.join(failed,'staging.json'))).status,'failed');assert.deepEqual(await readFile(path.join(rootDir,'public/data/database.json')),dbBytes);assert.deepEqual(await readFile(path.join(rootDir,'public/data/homegrown.json')),hgBytes);assert.equal(await readFile(path.join(rootDir,'saves/existing-career.json'),'utf8'),'THIS FILE MUST NEVER CHANGE');
});
