#!/usr/bin/env python3
"""Refresh venue names from ESPN home fixtures; never invent sourced capacities."""
import concurrent.futures
import datetime
import json
import pathlib
import subprocess

ROOT = pathlib.Path(__file__).resolve().parents[1]
CHECKED = datetime.datetime.now(datetime.timezone.utc).date().isoformat()
database = json.loads((ROOT / 'public/data/database.json').read_text())
season = int(database.get('meta', {}).get('season', '2026/27')[:4])
clubs = [c for c in database['clubs'] if c['id'].startswith('e') and c['leagueId'] in
         ('eng.1', 'esp.1', 'ger.1', 'ita.1', 'fra.1', 'por.1', 'ned.1')]
countries = {l['id']: l.get('countryCode', 'EU') for l in database['leagues']}


def fetch(club):
    url = f"https://site.api.espn.com/apis/site/v2/sports/soccer/{club['leagueId']}/teams/{club['id'][1:]}/schedule?season={season}"
    result = subprocess.run(['curl', '--fail', '--silent', '--show-error', '--retry', '1',
                             '--max-time', '20', url], capture_output=True, text=True)
    if result.returncode:
        return club['id'], None, result.stderr.strip()
    try:
        payload = json.loads(result.stdout)
        candidates = []
        for event in payload.get('events', []):
            for match in event.get('competitions', []):
                if match.get('neutralSite'):
                    continue
                home = next((c for c in match.get('competitors', []) if c.get('homeAway') == 'home'), {})
                ground = match.get('venue', {})
                if home.get('id') == club['id'][1:] and ground.get('fullName'):
                    candidates.append((event.get('date', ''), ground))
        if not candidates:
            return club['id'], None, 'No non-neutral home venue in source schedule'
        date, ground = max(candidates, key=lambda item: item[0])
        address = ground.get('address', {})
        record = {'name': ground['fullName'], 'city': address.get('city', ''),
                  'countryCode': countries[club['leagueId']], 'sourceName': 'ESPN home fixture',
                  'sourceUrl': url, 'sourceDate': date[:10], 'checkedAt': CHECKED,
                  'capacityEstimated': True, 'nameEstimated': False}
        # The current endpoint supplies names and cities, not usable capacity.
        return club['id'], record, None
    except (ValueError, KeyError, TypeError) as exc:
        return club['id'], None, str(exc)


records, errors = {}, []
with concurrent.futures.ThreadPoolExecutor(max_workers=6) as pool:
    for club_id, venue, error in pool.map(fetch, clubs):
        if venue:
            records[club_id] = venue
        else:
            errors.append({'clubId': club_id, 'error': error})
snapshot = {'checkedAt': CHECKED, 'season': season, 'count': len(records), 'venues': records,
            'notes': 'Stadium names from non-neutral home fixtures. Capacity remains estimated unless separately verified.'}
target = ROOT / 'src/stadium-data.mjs'
if len(records) < len(clubs) * .85:
    raise SystemExit(f'Refusing partial update: {len(records)}/{len(clubs)} venues. {errors}')
target.write_text('// Generated by scripts/import-stadiums.py; source URLs are retained per venue.\nexport default ' +
                  json.dumps(snapshot, ensure_ascii=False, indent=2) + ';\n')
print(json.dumps({'imported': len(records), 'requested': len(clubs), 'errors': errors}, ensure_ascii=False))
