import {nextSuspension,hasScopedBan} from './playerStatus.mjs';
import React,{useEffect,useMemo,useState} from 'react';
import {ArrowDownLeft,ArrowRight,ArrowSquareOut,ArrowUpRight,ArrowsLeftRight,CalendarBlank,Check,CurrencyEur,MapPin,MagnifyingGlass,ShieldCheck,Trophy,UsersThree,WarningCircle} from '@phosphor-icons/react';
import {Badge,Empty,Form,Meter,Modal,PageTitle,PlayerName,Rating,PlayerPosition,PositionOptions} from './components.jsx';
import {clubPlayers,dateLabel,money,overall,POSITION,table} from './engine.mjs';
import {competition,CUP_PHASES} from './competitions.mjs';
import {flag,nationality,number} from './locale.mjs';
import {staffMembers,STAFF_ROLES,STAFF_SKILLS,STAFF_TASKS,workload} from './staff.mjs';
import './clubs.css';
import {StadiumInfo} from './MatchEnvironment.jsx';
import {matchesPosition,positionLabel} from './playerPositions.mjs';

const normalize=s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replaceAll('đ','d');
const initials=name=>String(name).split(/\s+/).map(s=>s[0]).filter(Boolean).slice(-2).join('').toUpperCase();
const readableDate=value=>value?dateLabel(value):'Chưa có ngày';
const fixtureYear=(g,f)=>f.year||g.year;
const fixtureLabel=(g,f)=>f.leagueId==='friendly'?'Giao hữu':competition(g,f.leagueId)?.shortName||competition(g,f.leagueId)?.name||'Giải đấu';
const fixtureStage=f=>f.leagueId==='friendly'?'Giao hữu':f.matchday?`Vòng ${f.matchday}`:CUP_PHASES[f.stage]||'Lịch quốc nội';
const compareFixtures=(a,b)=>String(a.date||'').localeCompare(String(b.date||''))||(a.round||0)-(b.round||0)||a.id.localeCompare(b.id);

function Directory({g,clubId,onSelect}){
 const [q,setQ]=useState(''),[league,setLeague]=useState(''),[limit,setLimit]=useState(40),[expanded,setExpanded]=useState(false);
 const clubs=useMemo(()=>Object.values(g.clubs).sort((a,b)=>a.name.localeCompare(b.name)),[g.clubs]);
 const leagues=useMemo(()=>new Map(g.leagues.map(l=>[l.id,l])),[g.leagues]);
 const filtered=useMemo(()=>clubs.filter(c=>(!league||c.leagueId===league)&&normalize(c.name+' '+c.shortName+' '+c.abbreviation).includes(normalize(q))),[clubs,q,league]);
 const choose=id=>{onSelect(id);setExpanded(false);};
 return <aside className={'club-directory panel '+(expanded?'expanded':'')}><div className="club-directory-heading"><span><MagnifyingGlass size={17}/><strong>Tìm câu lạc bộ</strong></span><span>{number(clubs.length)}</span><button type="button" className="text-button club-directory-toggle" aria-expanded={expanded} onClick={()=>setExpanded(v=>!v)}>{expanded?'Thu gọn':'Mở danh sách'}</button></div><div className="club-directory-body"><div className="search"><MagnifyingGlass size={16}/><input aria-label="Tìm câu lạc bộ theo tên" placeholder="Tên CLB…" value={q} onChange={e=>{setQ(e.target.value);setLimit(40);}}/></div><select aria-label="Lọc câu lạc bộ theo giải đấu" value={league} onChange={e=>{setLeague(e.target.value);setLimit(40);}}><option value="">Tất cả giải đấu</option>{g.leagues.map(l=><option key={l.id} value={l.id}>{l.name}</option>)}</select><p className="club-directory-count">{number(filtered.length)} CLB phù hợp</p><div className="club-directory-list" role="group" aria-label="Danh sách câu lạc bộ">{filtered.slice(0,limit).map(c=><button type="button" className={c.id===clubId?'selected':''} aria-pressed={c.id===clubId} key={c.id} onClick={()=>choose(c.id)}><Badge club={c} size={29}/><span><strong>{c.name}</strong><small>{leagues.get(c.leagueId)?.name||'Đối thủ UEFA'}</small></span>{c.id===g.clubId&&<span className="club-own-dot" title="CLB của bạn"/>}{c.id===clubId&&<Check size={14}/>}</button>)}{!filtered.length&&<p className="club-directory-none">Không có CLB phù hợp.</p>}{filtered.length>limit&&<button type="button" className="club-directory-more" onClick={()=>setLimit(n=>n+40)}>Xem thêm {Math.min(40,filtered.length-limit)} CLB</button>}</div></div></aside>;
}

function ClubSquad({g,club,openPlayer}){
 const [q,setQ]=useState(''),[position,setPosition]=useState(''),[sort,setSort]=useState('overall');
 const players=clubPlayers(g,club.id),visible=players.filter(p=>matchesPosition(p,position)&&normalize(p.name).includes(normalize(q))).sort((a,b)=>sort==='name'?a.name.localeCompare(b.name):sort==='age'?a.age-b.age:sort==='value'?b.value-a.value:sort==='potential'?b.potential-a.potential:overall(b)-overall(a));
 return <><div className="club-squad-toolbar"><div className="search"><MagnifyingGlass size={16}/><input aria-label={'Tìm cầu thủ của '+club.name} placeholder="Tìm cầu thủ…" value={q} onChange={e=>setQ(e.target.value)}/></div><select aria-label="Lọc vị trí trong CLB" value={position} onChange={e=>setPosition(e.target.value)}><option value="">Mọi vị trí</option><PositionOptions/></select><select aria-label="Sắp xếp cầu thủ CLB" value={sort} onChange={e=>setSort(e.target.value)}><option value="overall">Năng lực</option><option value="potential">Tiềm năng</option><option value="value">Giá trị</option><option value="age">Tuổi tăng dần</option><option value="name">Tên A–Z</option></select></div><div className="panel table-scroll"><table className="club-player-table"><thead><tr><th>Số</th><th>Cầu thủ</th><th>Vị trí</th><th>NL</th><th>Tiềm năng</th><th>Thể lực</th><th>Giá trị</th><th>Tình trạng</th></tr></thead><tbody>{visible.map(p=><tr key={p.id}><td className="muted">{p.number||'—'}</td><td><PlayerName player={p} onClick={openPlayer} sub={`${flag(p)} ${nationality(p)} · ${p.age} tuổi`}/></td><td><PlayerPosition player={p}/></td><td><Rating player={p} small/></td><td className="lime">{number(p.potential)}</td><td><span className="meter-cell"><Meter value={p.fitness}/><small>{number(p.fitness)}%</small></span></td><td>{money(p.value)}</td><td>{p.injury?<span className="status-bad">Chấn thương · {number(p.injury)} tuần</span>:nextSuspension(g,p)?<span className="status-bad">Treo giò · {number(nextSuspension(g,p))} trận</span>:<span className="status-good">Sẵn sàng</span>}</td></tr>)}</tbody></table>{!visible.length&&<Empty>Không có cầu thủ phù hợp với bộ lọc.</Empty>}</div><p className="fine-print">{number(players.length)} cầu thủ trong đội hiện tại. Chọn tên để xem hồ sơ, theo dõi hoặc đàm phán chuyển nhượng.</p></>;
}

function StaffProfile({g,member,onClose}){
 const role=STAFF_ROLES[member.role],load=workload(g,member.id),specialist=role?.skills||[];
 return <Modal title="Hồ sơ nhân sự CLB" wide onClose={onClose}><div className="club-staff-profile"><div className="club-staff-profile-hero"><span className="club-staff-avatar large">{initials(member.name)}</span><div><span className={'club-person-source '+(member.sourceKind==='official'?'official':'')}>{member.sourceKind==='official'?'Có nguồn chính thức':'Nhân sự mô phỏng'}</span><h2>{member.name}</h2><p>{role?.label||member.role}</p><span className="club-inline"><Badge club={g.clubs[member.clubId]} size={20}/>{g.clubs[member.clubId]?.name}</span></div></div><div className="club-staff-facts"><div><span>Lương mỗi tuần</span><strong>{money(member.wage)}</strong></div><div><span>Phòng ban</span><strong>{role?.department}</strong></div><div><span>Khối lượng công việc</span><strong className={load.overloaded?'amber':''}>{load.count}/{load.capacity} nhiệm vụ</strong></div></div><div className="club-staff-profile-body"><h3>Năng lực chuyên môn <small>Chỉ số mô phỏng · /20</small></h3><div className="club-staff-skills">{Object.entries(STAFF_SKILLS).map(([key,label])=><div key={key} className={specialist.includes(key)?'specialist':''}><span>{label}</span><b>{number(member.attributes?.[key])}</b><Meter value={Number(member.attributes?.[key]||0)*5} tone={specialist.includes(key)?'var(--lime)':'#89a277'}/></div>)}</div><h3>Nhiệm vụ được phân công</h3>{load.tasks.length?<div className="club-staff-duties">{load.tasks.map(task=><span key={task}>{STAFF_TASKS[task]?.label||task}</span>)}</div>:<p className="club-staff-no-duty">Chưa được giao nhiệm vụ điều hành.</p>}{load.overloaded&&<p className="club-staff-overload"><WarningCircle size={16}/>Kiêm nhiệm quá 3 công việc làm giảm hiệu quả chuyên môn.</p>}<div className="club-staff-provenance"><ShieldCheck size={18}/><div><strong>{member.sourceKind==='official'?'Danh tính được đối chiếu từ nguồn công khai':'Nhân sự được tạo cho thế giới mô phỏng'}</strong><p>{member.sourceKind==='official'?'Các chỉ số và tiền lương là mô phỏng của game.':'Tên, vai trò, chỉ số và lương không đại diện cho nhân sự thật của câu lạc bộ.'}</p>{member.sourceRole&&<p>Chức danh tại nguồn: {member.sourceRole}.</p>}{member.sourceKind==='official'&&/^https?:\/\//.test(member.sourceUrl||'')&&<a href={member.sourceUrl} target="_blank" rel="noreferrer">{member.sourceLabel||'Xem nguồn'} <ArrowSquareOut size={12}/></a>}{member.checkedAt&&<small>Đối chiếu: {readableDate(member.checkedAt)}</small>}</div></div></div></div></Modal>;
}

function ClubStaff({g,club}){
 const [department,setDepartment]=useState(''),[profile,setProfile]=useState(null),members=staffMembers(g,club.id),groups=[...new Set(Object.values(STAFF_ROLES).map(r=>r.department))],visible=members.filter(s=>!department||STAFF_ROLES[s.role]?.department===department),selected=members.find(s=>s.id===profile);
 return <><div className="club-staff-toolbar"><p>{number(members.length)} thành viên · {Object.keys(STAFF_ROLES).length} vai trò chuyên môn</p><select aria-label="Lọc bộ phận nhân sự CLB" value={department} onChange={e=>setDepartment(e.target.value)}><option value="">Tất cả phòng ban</option>{groups.map(name=><option key={name} value={name}>{name}</option>)}</select></div><div className="club-staff-grid">{visible.map(member=>{const role=STAFF_ROLES[member.role],load=workload(g,member.id),skills=role?.skills||[],score=skills.length?skills.reduce((sum,k)=>sum+Number(member.attributes?.[k]||0),0)/skills.length:0;return <button className="club-staff-person panel" type="button" key={member.id} onClick={()=>setProfile(member.id)} aria-label={'Xem nhân sự '+member.name}><span className="club-staff-avatar">{initials(member.name)}</span><span className="club-staff-person-info"><small>{role?.label||member.role}</small><strong>{member.name}</strong><span className={'club-person-source '+(member.sourceKind==='official'?'official':'')}>{member.sourceKind==='official'?'Có nguồn chính thức':'Nhân sự mô phỏng'}</span></span><span className="club-staff-person-score"><b>{number(score,1)}</b><small>/20</small></span><span className="club-staff-person-footer"><span className={load.overloaded?'amber':''}>{load.count} nhiệm vụ{load.overloaded?' · Quá tải':''}</span><span>{money(member.wage)} / tuần</span></span></button>;})}</div>{!visible.length&&<Empty>Không có nhân sự trong bộ phận này.</Empty>}<p className="fine-print">Chọn thành viên để xem chuyên môn và nhiệm vụ. Phân công của CLB bạn được điều chỉnh tại mục Ban huấn luyện.</p>{selected&&<StaffProfile g={g} member={selected} onClose={()=>setProfile(null)}/>}</>;
}

function ClubFixtures({g,club,onSelectClub,openResult}){
 const [status,setStatus]=useState('all'),[league,setLeague]=useState(''),[year,setYear]=useState(String(g.year));
 const matches=useMemo(()=>[...(g.fixtures||[]),...(g.friendlies||[])].filter(f=>f.home===club.id||f.away===club.id).sort(compareFixtures),[g.fixtures,g.friendlies,club.id]);
 const years=[...new Set([g.year,...matches.map(f=>fixtureYear(g,f))])].sort((a,b)=>b-a),competitions=[...new Set(matches.map(f=>f.leagueId))];
 const visible=matches.filter(f=>(!year||String(fixtureYear(g,f))===year)&&(!league||f.leagueId===league)&&(status==='all'||(status==='played'?!!f.result:status==='cancelled'?f.cancelled:!f.result&&!f.cancelled)));
 return <><div className="club-fixture-toolbar"><div className="segmented">{[['all','Tất cả'],['upcoming','Sắp tới'],['played','Đã đấu']].map(([key,label])=><button type="button" key={key} className={status===key?'active':''} onClick={()=>setStatus(key)}>{label}</button>)}</div><select aria-label="Mùa giải trong lịch CLB" value={year} onChange={e=>setYear(e.target.value)}><option value="">Mọi mùa có dữ liệu</option>{years.map(y=><option key={y} value={y}>Mùa {y}/{String(y+1).slice(-2)}</option>)}</select><select aria-label="Đấu trường trong lịch CLB" value={league} onChange={e=>setLeague(e.target.value)}><option value="">Mọi đấu trường</option>{competitions.map(id=><option value={id} key={id}>{id==='friendly'?'Giao hữu':competition(g,id)?.name||id}</option>)}</select></div><div className="panel club-fixture-list">{visible.map(f=>{const home=f.home===club.id,opponent=g.clubs[home?f.away:f.home],ownScore=f.result?.score?.[home?0:1],otherScore=f.result?.score?.[home?1:0],outcome=f.result?(f.result.penalties&&f.result.winner?(f.result.winner===club.id?'win':'loss'):ownScore>otherScore?'win':ownScore<otherScore?'loss':'draw'):'';return <article className={'club-fixture-row '+(f.round===g.round&&!f.result&&!f.cancelled&&fixtureYear(g,f)===g.year?'current':'')} key={f.id}><div className="club-fixture-context"><strong>{fixtureLabel(g,f)}</strong><small>{readableDate(f.date)} · {fixtureStage(f)}</small></div><span className={'club-fixture-venue '+(home?'home':'')}>{home?'Sân nhà':'Sân khách'}</span><button type="button" className="club-opponent" onClick={()=>onSelectClub(opponent.id)}><Badge club={opponent} size={29}/><strong>{opponent.shortName||opponent.name}</strong><ArrowRight size={13}/></button><div className={'club-fixture-score '+outcome}>{f.cancelled?<span>Đã hủy</span>:f.result?<><strong>{ownScore} – {otherScore}</strong><small>{outcome==='win'?'Thắng':outcome==='loss'?'Thua':'Hòa'}{f.result.penalties?' · Luân lưu':''}</small></>:<span>Chưa đấu</span>}</div>{f.result?<button type="button" className="small-button" onClick={()=>openResult(f)} aria-label={'Báo cáo trận '+club.name+' gặp '+opponent.name+' ngày '+readableDate(f.date)}>Báo cáo</button>:<span className="club-fixture-unplayed">{f.cancelled?'—':f.round===g.round&&fixtureYear(g,f)===g.year?'Mốc hiện tại':'Sắp tới'}</span>}</article>;})}{!visible.length&&<Empty>Không có trận đấu phù hợp với bộ lọc. Các vòng loại trực tiếp tiếp theo xuất hiện sau khi vòng trước kết thúc.</Empty>}</div><p className="fine-print">Tỷ số hiển thị {club.shortName||club.name} trước, đối thủ sau. Lịch và kết quả thuộc sự nghiệp đang chơi.</p></>;
}

function ClubTransfers({g,club,onSelectClub,openPlayer}){
 const [direction,setDirection]=useState('all'),[season,setSeason]=useState('all');
 const transferYear=t=>{if(Number.isInteger(t.season))return t.season;const [year,month]=String(t.date||'').split('-').map(Number);return Number.isFinite(year)&&Number.isFinite(month)?year-(month<7?1:0):null;};
 const transfers=(g.transfers||[]).filter(t=>t.from===club.id||t.to===club.id),years=[...new Set(transfers.map(transferYear).filter(Boolean))].sort((a,b)=>b-a),inSeason=transfers.filter(t=>season==='all'||String(transferYear(t))===season),incoming=inSeason.filter(t=>t.to===club.id),outgoing=inSeason.filter(t=>t.from===club.id),spent=incoming.reduce((sum,t)=>sum+Number(t.fee||0),0),earned=outgoing.reduce((sum,t)=>sum+Number(t.fee||0),0),visible=inSeason.filter(t=>direction==='all'||(direction==='in'?t.to===club.id:t.from===club.id));
 return <><div className="club-transfer-summary"><div><span><ArrowDownLeft size={16}/>Chiêu mộ · {number(incoming.length)}</span><strong>{money(spent)}</strong><small>Tổng phí chi</small></div><div><span><ArrowUpRight size={16}/>Rời CLB · {number(outgoing.length)}</span><strong>{money(earned)}</strong><small>Tổng phí thu</small></div><div><span><CurrencyEur size={16}/>Cán cân chuyển nhượng</span><strong className={earned>=spent?'lime':''}>{earned>=spent?'+':''}{money(earned-spent)}</strong><small>Thu trừ chi</small></div></div><div className="club-transfer-toolbar"><div className="segmented">{[['all','Tất cả'],['in','Đến CLB'],['out','Rời CLB']].map(([key,label])=><button type="button" key={key} className={direction===key?'active':''} onClick={()=>setDirection(key)}>{label}</button>)}</div><select aria-label="Mùa chuyển nhượng của CLB" value={season} onChange={e=>setSeason(e.target.value)}><option value="all">Toàn bộ sự nghiệp</option>{years.map(y=><option value={y} key={y}>Mùa {y}/{String(y+1).slice(-2)}</option>)}</select></div><div className="panel club-transfer-list">{visible.map((transfer,index)=>{const incoming=transfer.to===club.id,person=g.players[transfer.playerId||transfer.id],counterparty=g.clubs[incoming?transfer.from:transfer.to];return <article className="club-transfer-row" key={`${transfer.eventId||transfer.id||'transfer'}-${index}`}><span className={'club-transfer-direction '+(incoming?'incoming':'outgoing')} title={incoming?'Gia nhập':'Rời CLB'}>{incoming?<ArrowDownLeft size={19}/>:<ArrowUpRight size={19}/>}</span><div className="club-transfer-player">{person?<PlayerName player={person} onClick={openPlayer} sub={`${positionLabel(person)} · ${incoming?'Gia nhập CLB':'Rời CLB'}`}/>:<strong>{transfer.name||'Cầu thủ'}</strong>}</div><div className="club-transfer-counterparty"><small>{incoming?'Từ':'Đến'}</small>{counterparty?<button type="button" onClick={()=>onSelectClub(counterparty.id)}><Badge club={counterparty} size={23}/><span>{counterparty.shortName||counterparty.name}</span><ArrowSquareOut size={12}/></button>:<span>CLB chưa rõ</span>}</div><div className="club-transfer-price"><strong>{money(transfer.fee)}</strong><small>{readableDate(transfer.date)}</small></div></article>;})}{!visible.length&&<Empty>{transfers.length?'Không có giao dịch phù hợp với bộ lọc.':'Chưa có chuyển nhượng được ghi nhận cho CLB này trong sự nghiệp.'}</Empty>}</div><p className="fine-print">Lịch sử ghi lại giao dịch của bạn và giữa các CLB trong thế giới mô phỏng. Chuyển nhượng thực tế trước khi bắt đầu sự nghiệp không được thêm vào sổ này.</p></>;
}

export default function ClubPage({g,clubId,onSelectClub,openPlayer,openResult}){
 const club=g.clubs[clubId]||g.clubs[g.clubId],[tab,setTab]=useState('players');
 useEffect(()=>{setTab('players');},[club.id]);
 const league=competition(g,club.leagueId),players=clubPlayers(g,club.id),members=staffMembers(g,club.id),rows=useMemo(()=>table(g,club.leagueId),[g,club.leagueId]),standing=rows.find(r=>r.clubId===club.id),rank=rows.findIndex(r=>r.clubId===club.id)+1,hasLeagueMatches=rows.some(r=>r.played>0),averageAge=players.length?players.reduce((sum,p)=>sum+p.age,0)/players.length:0,teamValue=players.reduce((sum,p)=>sum+p.value,0),tabs=[['players','Cầu thủ',UsersThree,players.length],['staff','Ban huấn luyện',ShieldCheck,members.length],['fixtures','Lịch thi đấu',CalendarBlank],['transfers','Chuyển nhượng',ArrowsLeftRight]];
 return <div className="club-page"><PageTitle eyebrow="THẾ GIỚI BÓNG ĐÁ" title="Câu lạc bộ" description="Theo dõi đội hình, bộ máy chuyên môn và hoạt động của mọi CLB trong sự nghiệp." action={club.id!==g.clubId?<button type="button" className="secondary" onClick={()=>onSelectClub(g.clubId)}><Badge club={g.clubs[g.clubId]} size={20}/>CLB của tôi</button>:undefined}/><div className="club-browser-layout"><Directory g={g} clubId={club.id} onSelect={onSelectClub}/><div className="club-detail"><section className="club-hero panel"><div className="club-hero-main"><div className="club-hero-badge"><Badge club={club} size={82}/></div><div className="club-hero-identity"><span className="club-hero-country">{league?.country||'Châu Âu'} · {league?.name||'Đối thủ UEFA'}</span><h1>{club.name}</h1><div>{club.stadium&&<span><MapPin size={14}/>{club.stadium}</span>}{club.id===g.clubId&&<span className="club-managed"><Check size={12}/>Đội của bạn</span>}</div></div><div className="club-reputation"><strong>{number(club.reputation)}</strong><span>Danh tiếng /100</span></div></div><div className="club-hero-bottom"><span><Trophy size={15}/>{hasLeagueMatches&&rank?`Hạng ${rank} / ${rows.length}`:'Chưa xếp hạng'}{standing?` · ${number(standing.points)} điểm`:''}</span><span className="club-league-form"><small>Phong độ giải quốc nội</small><Form results={standing?.form||[]}/></span></div></section><div className="club-key-facts"><div><span>Đội một</span><strong>{number(players.length)}<small> cầu thủ</small></strong></div><div><span>Tuổi trung bình</span><strong>{number(averageAge,1)}<small> tuổi</small></strong></div><div><span>Giá trị đội hình</span><strong>{money(teamValue)}</strong></div></div><StadiumInfo g={g} clubId={club.id}/><div className="club-detail-tabs" role="group" aria-label="Nội dung câu lạc bộ">{tabs.map(([key,label,Icon,count])=><button type="button" key={key} className={tab===key?'active':''} aria-pressed={tab===key} onClick={()=>setTab(key)}><Icon size={17}/>{label}{count!==undefined&&<span>{number(count)}</span>}</button>)}</div><div key={club.id} className="club-tab-content">{tab==='players'&&<ClubSquad g={g} club={club} openPlayer={openPlayer}/>} {tab==='staff'&&<ClubStaff g={g} club={club}/>} {tab==='fixtures'&&<ClubFixtures g={g} club={club} onSelectClub={onSelectClub} openResult={openResult}/>} {tab==='transfers'&&<ClubTransfers g={g} club={club} onSelectClub={onSelectClub} openPlayer={openPlayer}/>}</div></div></div></div>;
}
