import React,{useState} from 'react';
import {competitionPlayerStats,competitionTeamStats} from './competitionStats.mjs';
import {PlayerName,ClubLink,Empty} from './components.jsx';
import {number} from './locale.mjs';
export default function CompetitionStats({g,id,teams=false,openPlayer}){
 const [sort,setSort]=useState('goals'),[page,setPage]=useState(0);
 const rows=teams?competitionTeamStats(g,id):competitionPlayerStats(g,id,sort),pages=Math.max(1,Math.ceil(rows.length/30)),current=Math.min(page,pages-1);
 return <div className="panel"><div className="toolbar padded">{!teams&&<select aria-label="Xếp thống kê cầu thủ" value={sort} onChange={e=>{setSort(e.target.value);setPage(0);}}><option value="goals">Bàn thắng</option><option value="assists">Kiến tạo</option><option value="appearances">Trận</option></select>}<p className="fine-print">Thống kê mùa hiện tại của giải đã chọn, gồm cả vòng loại trực tiếp. CLB của cầu thủ là đội hiện tại.</p></div><div className="table-scroll"><table className="player-table"><thead><tr><th>#</th><th>{teams?'CLB':'Cầu thủ'}</th>{!teams&&<th>CLB</th>}<th>Trận</th><th>Bàn thắng</th>{teams?<><th>Bàn thua</th><th>Thắng</th><th>Hòa</th><th>Thua</th><th>Giữ sạch lưới</th></>:<th>Kiến tạo</th>}</tr></thead><tbody>{rows.slice(current*30,current*30+30).map((r,i)=>teams?<tr key={r.clubId}><td>{number(current*30+i+1)}</td><td><ClubLink club={g.clubs[r.clubId]}/></td>{['played','gf','ga','won','drawn','lost','cleanSheets'].map(k=><td key={k}>{number(r[k])}</td>)}</tr>:<tr key={r.p.id}><td>{number(current*30+i+1)}</td><td><PlayerName player={r.p} onClick={openPlayer}/></td><td><ClubLink club={g.clubs[r.p.clubId]}/></td>{['appearances','goals','assists'].map(k=><td key={k}>{number(r.stat[k]||0)}</td>)}</tr>)}</tbody></table></div>{!rows.length&&<Empty>Chưa có thống kê thi đấu.</Empty>}<div className="pagination"><span>Trang {current+1}/{pages}</span><button disabled={current===0} onClick={()=>setPage(current-1)}>Trước</button><button disabled={current>=pages-1} onClick={()=>setPage(current+1)}>Sau</button></div></div>;
}
