import React,{useState} from 'react';
import {EnvelopeSimple,EnvelopeOpen,Check,ArrowRight,MagnifyingGlass} from '@phosphor-icons/react';
import {PageTitle,Empty} from './components.jsx';
import {dateLabel} from './engine.mjs';
import {mailParagraphs} from './mail.mjs';
const labels={staff:'Ban huấn luyện',friendly:'Giao hữu',press:'Truyền thông',scouting:'Tuyển trạch',youth:'Đào tạo trẻ',board:'Ban lãnh đạo',match:'Báo cáo trận',transfer:'Chuyển nhượng',season:'Mùa giải',medical:'Y tế',finance:'Tài chính',registration:'Đăng ký'};
export default function Inbox({g,mutate,nav}){
 const [selected,setSelected]=useState(null),[query,setQuery]=useState(''),[unread,setUnread]=useState(false);
 const messages=g.messages.filter(m=>(!unread||!m.readAt)&&`${m.title} ${m.body} ${m.sender}`.toLocaleLowerCase('vi').includes(query.toLocaleLowerCase('vi')));
 const current=g.messages.find(m=>m.id===selected);const count=g.messages.filter(m=>!m.readAt).length;
 const open=id=>{setSelected(id);if(!g.messages.find(m=>m.id===id)?.readAt)mutate(x=>{x.messages.find(m=>m.id===id).readAt=x.date;});};
 return <><PageTitle eyebrow="VĂN PHÒNG" title="Hộp thư" description={`${count} thư chưa đọc · Báo cáo và trao đổi nội bộ CLB`} action={<button className="secondary" disabled={!count} onClick={()=>mutate(x=>x.messages.forEach(m=>{m.readAt||=x.date;}))}><Check/>Đánh dấu đã đọc tất cả</button>}/><div className="toolbar"><div className="search"><MagnifyingGlass/><input aria-label="Tìm thư" placeholder="Tìm trong hộp thư…" value={query} onChange={e=>setQuery(e.target.value)}/></div><label className="check-label"><input type="checkbox" checked={unread} onChange={e=>setUnread(e.target.checked)}/>Chỉ thư chưa đọc</label></div><div className="mail-layout"><div className="panel mail-list">{messages.map(m=><button key={m.id} className={`mail-preview ${m.readAt?'':'unread'} ${selected===m.id?'selected':''}`} onClick={()=>open(m.id)}><span className="mail-preview-icon">{m.readAt?<EnvelopeOpen size={21}/>:<EnvelopeSimple size={21} weight="fill"/>}</span><div><div className="mail-preview-meta"><span>{m.sender||labels[m.type]||'Văn phòng CLB'}</span><time>{dateLabel(m.date)}</time></div><strong>{m.title}</strong><p>{m.body}</p></div></button>)}{!messages.length&&<Empty>Không có thư phù hợp.</Empty>}</div><article className="panel mail-reader">{current?<><div className="mail-reader-heading"><span className="tag">{labels[current.type]||'Thông báo'}</span><h2>{current.title}</h2><dl><dt>Từ</dt><dd>{current.sender||'Văn phòng CLB'}</dd><dt>Đến</dt><dd>{current.to||g.manager}</dd><dt>Ngày gửi</dt><dd>{dateLabel(current.date)}</dd></dl></div><div className="mail-body">{mailParagraphs(current,g).map((p,i)=><p key={i}>{p}</p>)}</div>{current.action&&<button className="secondary" onClick={()=>nav(current.action.page)}>{current.action.label}<ArrowRight/></button>}</>:<div className="mail-empty"><EnvelopeOpen size={52}/><h2>Chọn một bức thư</h2><p>Nội dung đầy đủ sẽ xuất hiện tại đây.<br/>Thư đã đọc được lưu cùng sự nghiệp.</p></div>}</article></div></>;
}
