import {getLocale,number} from './locale.mjs';
import React,{useEffect,useRef,useState} from 'react';
import {FolderOpen,Play,FloppyDisk,ArrowSquareIn,ArrowsClockwise,PencilSimple,Check,X,MagnifyingGlass,Trash,HardDrives} from '@phosphor-icons/react';
import {filterSortSaves,normalizeSlotName,saveSummary} from './saveSlots.mjs';
import {Modal} from './components.jsx';
import './saved-games.css';

export const formatSaveDate=(value,withTime=false)=>{if(!value||!Number.isFinite(Date.parse(value)))return 'Chưa rõ';return new Date(value).toLocaleString(getLocale(),{day:'2-digit',month:'2-digit',year:'numeric',...(withTime?{hour:'2-digit',minute:'2-digit'}:{})});};
export const formatStorage=bytes=>!Number.isFinite(bytes)||bytes<0?'—':bytes>0&&bytes<10000?'< '+number(.01,2)+' MB':number(bytes/1000000,2)+' MB';

/** Action handlers own all persistence; this component only manages forms. */
export default function SavedGames({saves=[],onLoad,onImport,onRefresh,onSaveAs,onRename,onDelete,currentGame=null,busy=false,refreshing=false}){
 const [query,setQuery]=useState(''),[sort,setSort]=useState('updated'),[copyName,setCopyName]=useState(''),[editing,setEditing]=useState(null),[editName,setEditName]=useState(''),[pending,setPending]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const [deleteSlot,setDeleteSlot]=useState(null),cancelDeleteRef=useRef(null),pendingRef=useRef(false),busyRef=useRef(busy);busyRef.current=busy;
 const rows=filterSortSaves(saves,{query,sort}),current=currentGame?saveSummary(currentGame):null,locked=busy||!!pending;
 const storageBytes=saves.reduce((sum,s)=>sum+(Number.isFinite(s.storageBytes)&&s.storageBytes>0?s.storageBytes:0),0);
 const action=async(key,fn,after)=>{if(busyRef.current||pendingRef.current)return;pendingRef.current=true;setError('');setNotice('');setPending(key);try{const result=await fn();if(result!==false)after?.(result);}catch(e){setError(e.message||'Không thực hiện được thao tác.');}finally{pendingRef.current=false;setPending('');}};
 // Modal installs its Escape listener once; refs keep that listener aware of a pending delete.
 const closeDelete=()=>{if(!pendingRef.current&&!busyRef.current){setDeleteSlot(null);setError('');}};
 useEffect(()=>{if(!deleteSlot)return;const frame=requestAnimationFrame(()=>cancelDeleteRef.current?.focus());return()=>cancelAnimationFrame(frame);},[deleteSlot]);
 const remove=()=>{if(!deleteSlot||!onDelete||deleteSlot.id===currentGame?.id)return;action('delete-'+deleteSlot.id,()=>onDelete(deleteSlot.id),result=>{setDeleteSlot(null);setNotice(`Đã xóa bản lưu. Đã giải phóng ${formatStorage(result?.freedBytes)}.`);});};
 const create=e=>{e.preventDefault();action('save-as',()=>onSaveAs(normalizeSlotName(copyName)),()=>{setCopyName('');setNotice('Đã tạo bản lưu mới.');});};
 const rename=(e,id)=>{e.preventDefault();action('rename-'+id,()=>onRename(id,normalizeSlotName(editName)),()=>{setEditing(null);setNotice('Đã đổi tên bản lưu.');});};
 return <section className="saved-games" aria-label="Saved Games — các bản lưu">
  <header className="saved-games-heading"><div><span className="eyebrow">SỰ NGHIỆP TRÊN MÁY</span><h1><FolderOpen size={29}/>Saved Games</h1><p>{number(saves.length)} bản lưu · Chọn một sự nghiệp để tiếp tục đúng thời điểm đã lưu.</p><p className="saved-games-storage"><HardDrives size={16}/><span>Dung lượng trên máy: <strong>{formatStorage(storageBytes)}</strong> · Gồm bản sao dự phòng.</span></p></div><div className="saved-games-actions">{onImport&&<button className="secondary" disabled={locked} onClick={onImport}><ArrowSquareIn size={17}/>Nhập file lưu</button>}{onRefresh&&<button className="secondary" disabled={locked||refreshing} onClick={()=>action('refresh',onRefresh)}><ArrowsClockwise size={17} className={refreshing||pending==='refresh'?'spin':''}/>Làm mới</button>}</div></header>
  {current&&onSaveAs&&<form className="save-as-form" onSubmit={create}><div><h2><FloppyDisk size={20}/>Lưu thành bản mới</h2><p>{current.club} · {current.manager} · {formatSaveDate(current.date)}{current.liveMinute!==null?` · Trận đấu phút ${current.liveMinute}′`:''}</p><small>Lưu toàn bộ tiến trình hiện tại vào một bản riêng, bao gồm đội hình và trận đang diễn ra.</small></div><label>Tên bản lưu mới<input value={copyName} onChange={e=>setCopyName(e.target.value)} placeholder={`${current.name} · Bản riêng`} maxLength={80} disabled={locked} required/></label><button className="primary" disabled={locked||!copyName.trim()}><FloppyDisk size={17}/>{pending==='save-as'?'Đang lưu…':'Save as · Lưu bản mới'}</button></form>}
  <div className="saved-games-toolbar"><label className="saved-games-search"><MagnifyingGlass size={19}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Tìm tên bản lưu, CLB, huấn luyện viên…" aria-label="Tìm bản lưu"/></label><label className="saved-games-sort">Sắp xếp<select aria-label="Sắp xếp bản lưu" value={sort} onChange={e=>setSort(e.target.value)}><option value="updated">Lưu gần nhất</option><option value="name">Tên bản lưu A–Z</option><option value="club">Câu lạc bộ A–Z</option><option value="date">Ngày trong game mới nhất</option></select></label></div>
  {error&&!deleteSlot&&<p className="save-message error" role="alert">{error}</p>}{notice&&<p className="save-message" role="status">{notice}</p>}
  <div className="saved-games-list">{rows.map(s=><article className={'save-slot '+(s.id===currentGame?.id?'is-current':'')} key={s.id}>
   <div className="save-slot-title"><div>{editing===s.id?<form className="save-rename-form" onSubmit={e=>rename(e,s.id)}><input aria-label="Tên mới của bản lưu" autoFocus value={editName} maxLength={80} onChange={e=>setEditName(e.target.value)} disabled={locked} required/><button className="icon-button" aria-label="Lưu tên bản lưu" disabled={locked||!editName.trim()}><Check size={18}/></button><button type="button" className="icon-button" aria-label="Hủy đổi tên" disabled={locked} onClick={()=>setEditing(null)}><X size={18}/></button></form>:<h2>{s.name}{onRename&&<button className="icon-button save-rename-button" aria-label={'Đổi tên '+s.name} disabled={locked} onClick={()=>{setEditing(s.id);setEditName(s.name);setError('');}}><PencilSimple size={15}/></button>}</h2>}<p><strong>{s.club}</strong><span>HLV {s.manager}</span>{s.id===currentGame?.id&&<span className="tag">Đang chơi</span>}{s.liveMinute!==null&&<span className="save-live">{s.liveCompleted?'Chờ ghi nhận kết quả':`Trận đang lưu · ${s.liveMinute}′`}</span>}</p></div><button className="primary save-load" disabled={locked||!onLoad} onClick={()=>action('load-'+s.id,()=>onLoad(s.id))}><Play size={16} weight="fill"/>{pending==='load-'+s.id?'Đang tải…':'Load Game'}</button></div>
   <dl className="save-slot-details"><div><dt>Ngày trong game</dt><dd>{formatSaveDate(s.date)}</dd></div><div><dt>Mùa giải</dt><dd>{s.season||'Chưa rõ'} <small>· Mốc {s.round+1}</small></dd></div><div><dt>Lưu lần cuối</dt><dd>{formatSaveDate(s.updatedAt,true)}</dd></div><div><dt>Dung lượng</dt><dd>{formatStorage(s.storageBytes)}<small>Gồm bản sao dự phòng</small></dd></div><div className="save-roster-detail"><dt>Bản dữ liệu đội hình</dt><dd>{s.dbReleaseLabel||s.dbReleaseId||'Bản dữ liệu gốc'}<small>{s.dbSeason?'Mùa '+s.dbSeason+' · ':''}{s.dbAsOf?'Mốc dữ liệu '+formatSaveDate(s.dbAsOf):'Chưa có mốc dữ liệu'}{s.dbReleaseLabel&&s.dbReleaseId?' · '+s.dbReleaseId:''}</small></dd></div></dl>
   {onDelete&&<footer className="save-slot-footer"><small>{s.id===currentGame?.id?'Về màn hình bắt đầu để xóa bản đang chơi.':'Xóa bản lưu để giải phóng dung lượng trên máy.'}</small><button type="button" className="secondary save-delete" aria-label={'Xóa bản lưu '+s.name} disabled={locked||s.id===currentGame?.id} onClick={()=>{setDeleteSlot(s);setError('');setNotice('');}}><Trash size={16}/>Xóa bản lưu</button></footer>}
  </article>)}</div>
  {!rows.length&&<div className="saved-games-empty"><FolderOpen size={38}/><h2>{saves.length?'Không tìm thấy bản lưu phù hợp':'Chưa có sự nghiệp được lưu'}</h2><p>{saves.length?'Thử tên CLB, tên huấn luyện viên hoặc xóa nội dung tìm kiếm.':'Chọn New Game để bắt đầu, hoặc nhập file lưu từ máy.'}</p>{query&&<button className="secondary" onClick={()=>setQuery('')}>Xóa tìm kiếm</button>}</div>}
  {rows.length>0&&query&&<p className="saved-games-count">Hiển thị {number(rows.length)} / {number(saves.length)} bản lưu.</p>}
  {deleteSlot&&<Modal title="Xóa bản lưu?" onClose={closeDelete}><div className="save-delete-dialog" aria-busy={pending==='delete-'+deleteSlot.id}>
   <p>Bản lưu này và các bản sao dự phòng trên máy sẽ bị xóa vĩnh viễn. Không thể hoàn tác.</p>
   <dl><div><dt>Tên bản lưu</dt><dd>{deleteSlot.name}</dd></div><div><dt>Câu lạc bộ</dt><dd>{deleteSlot.club}</dd></div><div><dt>Ngày trong game</dt><dd>{formatSaveDate(deleteSlot.date)}</dd></div><div><dt>Dung lượng có thể giải phóng</dt><dd>{formatStorage(deleteSlot.storageBytes)}</dd></div></dl>
   <p className="muted">Các file đã xuất riêng và những bản lưu khác vẫn được giữ nguyên.</p>
   {error&&<p className="save-message error" role="alert">{error}</p>}
   <div className="save-delete-dialog-actions"><button ref={cancelDeleteRef} type="button" className="secondary" disabled={locked} onClick={closeDelete}>Hủy</button><button type="button" className="save-delete-confirm" disabled={locked||deleteSlot.id===currentGame?.id} onClick={remove}><Trash size={17}/>{pending==='delete-'+deleteSlot.id?'Đang xóa…':'Xóa vĩnh viễn bản lưu'}</button></div>
  </div></Modal>}
 </section>;
}
