const rows=[
 ['title','Cài đặt','Settings','Paramètres','Ajustes','Definições'],
 ['subtitle','Ngôn ngữ, đơn vị và cách hiển thị số liệu','Language, units and number formatting','Langue, unités et format des nombres','Idioma, unidades y formato de números','Idioma, unidades e formato dos números'],
 ['language','Ngôn ngữ giao diện','Interface language','Langue de l’interface','Idioma de la interfaz','Idioma da interface'],
 ['languageHelp','Áp dụng ngay cho giao diện và cách hiển thị số, ngày. Tên cầu thủ, CLB và dữ liệu đã lưu không bị sửa. Thư theo mẫu có thể được dịch khi hiển thị; nội dung tự do chưa có bản dịch giữ ngôn ngữ gốc.','Changes the interface and number/date formats immediately. Player and club names and saved data are not modified. Recognised mail templates may be translated for display; free text without a translation keeps its original language.','Modifie immédiatement l’interface et les formats des nombres et des dates. Les noms et les données enregistrées ne sont pas modifiés. Les modèles de messages reconnus peuvent être traduits à l’affichage ; le texte libre sans traduction garde sa langue d’origine.','Cambia inmediatamente la interfaz y los formatos de números y fechas. No modifica nombres ni datos guardados. Los mensajes con plantillas reconocidas pueden traducirse al mostrarse; el texto libre sin traducción conserva su idioma original.','Altera imediatamente a interface e os formatos de números e datas. Não modifica nomes nem dados guardados. As mensagens com modelos reconhecidos podem ser traduzidas na apresentação; o texto livre sem tradução mantém o idioma original.'],
 ['units','Đơn vị hiển thị','Display units','Unités d’affichage','Unidades de visualización','Unidades de apresentação'],
 ['currency','Tiền tệ','Currency','Devise','Moneda','Moeda'],
 ['EUR','Euro (€)','Euro (€)','Euro (€)','Euro (€)','Euro (€)'],
 ['USD','Đô la Mỹ ($)','US dollar ($)','Dollar américain ($)','Dólar estadounidense ($)','Dólar americano ($)'],
 ['GBP','Bảng Anh (£)','Pound sterling (£)','Livre sterling (£)','Libra esterlina (£)','Libra esterlina (£)'],
 ['distance','Khoảng cách / chiều dài','Distance / length','Distance / longueur','Distancia / longitud','Distância / comprimento'],
 ['metric','Mét / kilômét (m, km)','Metres / kilometres (m, km)','Mètres / kilomètres (m, km)','Metros / kilómetros (m, km)','Metros / quilómetros (m, km)'],
 ['imperial','Yard / dặm (yd, mi)','Yards / miles (yd, mi)','Yards / miles (yd, mi)','Yardas / millas (yd, mi)','Jardas / milhas (yd, mi)'],
 ['height','Chiều cao','Height','Taille','Altura','Altura'],
 ['cm','Centimét (cm)','Centimetres (cm)','Centimètres (cm)','Centímetros (cm)','Centímetros (cm)'],
 ['ft','Feet / inch (ft, in)','Feet / inches (ft, in)','Pieds / pouces (ft, in)','Pies / pulgadas (ft, in)','Pés / polegadas (ft, in)'],
 ['weight','Cân nặng','Weight','Poids','Peso','Peso'],
 ['kg','Kilôgam (kg)','Kilograms (kg)','Kilogrammes (kg)','Kilogramos (kg)','Quilogramas (kg)'],
 ['lb','Pound (lb)','Pounds (lb)','Livres (lb)','Libras (lb)','Libras (lb)'],
 ['fx','Tỷ giá quy đổi trong game','In-game exchange rates','Taux de conversion dans le jeu','Tipos de cambio del juego','Taxas de câmbio no jogo'],
 ['fxHelp','Đây là tỷ giá mô phỏng có thể tự chỉnh, không phải tỷ giá trực tiếp. Đổi tiền tệ chỉ đổi cách hiển thị và nhập tiền; số dư, hợp đồng và giao dịch vẫn được lưu theo euro.','These are editable simulation rates, not live exchange rates. Currency changes affect display and money entry only; balances, contracts and transactions remain stored in euros.','Ces taux sont modifiables et simulés, pas des cours en direct. Le choix de devise modifie uniquement l’affichage et la saisie ; soldes, contrats et transactions restent enregistrés en euros.','Son tipos de cambio simulados y editables, no cotizaciones en tiempo real. La moneda solo cambia la visualización y la entrada de importes; saldos, contratos y operaciones siguen guardados en euros.','Estas taxas são simuladas e editáveis, não cotações em tempo real. A moeda altera apenas a apresentação e a introdução de valores; saldos, contratos e transações continuam guardados em euros.'],
 ['rate','1 EUR =','1 EUR =','1 EUR =','1 EUR =','1 EUR ='],
 ['preview','Xem trước','Preview','Aperçu','Vista previa','Pré-visualização'],
 ['budget','Ngân sách mẫu','Sample budget','Budget d’exemple','Presupuesto de ejemplo','Orçamento de exemplo'],
 ['pitch','Chiều dài sân mẫu','Sample pitch length','Longueur du terrain d’exemple','Longitud de campo de ejemplo','Comprimento de campo de exemplo'],
 ['travel','Quãng đường mẫu','Sample travel distance','Distance de trajet d’exemple','Distancia de viaje de ejemplo','Distância de viagem de exemplo'],
 ['date','Ngày tháng','Date','Date','Fecha','Data'],
 ['saved','Tự động lưu trên trình duyệt này. Áp dụng cho cả sự nghiệp mới và các bản save đang chơi.','Saved automatically in this browser. Applies to new careers and existing saves.','Enregistré automatiquement dans ce navigateur. S’applique aux nouvelles carrières et aux sauvegardes existantes.','Se guarda automáticamente en este navegador. Se aplica a carreras nuevas y partidas existentes.','Guardado automaticamente neste navegador. Aplica-se a novas carreiras e jogos guardados existentes.'],
 ['reset','Khôi phục mặc định','Restore defaults','Rétablir les valeurs par défaut','Restaurar valores predeterminados','Restaurar predefinições'],
];
export const settingsCatalog=Object.fromEntries(['vi','en','fr','es','pt'].map((lang,i)=>[lang,Object.fromEntries(rows.map(row=>[row[0],row[i+1]]))]));
