import AssessmentSources from './AssessmentSources.jsx';
import {getLocale} from './locale.mjs';
import React,{useState} from 'react';
import {SoccerBall,Play,FolderOpen,Check,Database,CircleNotch} from '@phosphor-icons/react';
import {Badge,Portrait} from './components.jsx';
import SavedGames,{formatSaveDate} from './SavedGames.jsx';

export default function StartScreen({db,saves=[],onNew,onLoad,onImport,onRename,onDelete,onRefresh,busy=false,rosterReleases=[],selectedReleaseId='',onSelectRelease,releaseBusy=false}){
 const [mode,setMode]=useState(()=>saves.length?'saved':'new'),[league,setLeague]=useState('esp.1'),[club,setClub]=useState('e83'),[manager,setManager]=useState('HLV'),[query,setQuery]=useState(''),[saveName,setSaveName]=useState('');
 const [sourceInjuries,setSourceInjuries]=useState(false);
 const selected=db.clubs.find(c=>c.id===club)||db.clubs.find(c=>c.leagueId===league)||db.clubs[0],activeLeague=db.leagues.find(l=>l.id===selected?.leagueId),country=activeLeague?.countryCode;
 const countries=[...new Map(db.leagues.filter(l=>l.kind!=='external').map(l=>[l.countryCode,{code:l.countryCode,name:l.country}])).values()];
 const players=db.players.filter(p=>p.clubId===selected?.id),star=players.find(p=>p.name==='Lamine Yamal')||players.find(p=>p.photo)||players[0];
 const activeRelease=rosterReleases.find(r=>r.id===selectedReleaseId)||db.meta.release||{},releaseDate=activeRelease.asOf||db.meta.asOf||db.meta.expandedAt||db.meta.importedAt,releaseSeason=activeRelease.season||db.meta.season,locked=busy||releaseBusy;
 const chooseLeague=id=>{setLeague(id);setQuery('');const first=db.clubs.find(c=>c.leagueId===id);if(first)setClub(first.id);};
 const normalize=value=>value.toLocaleLowerCase('vi').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replaceAll('đ','d');
 return <div className="start-screen">
  <header className="start-header"><span className="brand"><SoccerBall weight="duotone" size={30}/>touchline<span className="brand-edition">26</span></span><span className="local-label"><span/> CHƠI TRÊN MÁY CỦA BẠN</span></header>
  <nav className="start-mode-picker" aria-label="Bắt đầu hoặc tải sự nghiệp"><button className={mode==='new'?'active':''} aria-pressed={mode==='new'} onClick={()=>setMode('new')}><Play size={23}/><span><strong>New Game</strong><small>Bắt đầu sự nghiệp mới</small></span></button><button className={mode==='saved'?'active':''} aria-pressed={mode==='saved'} onClick={()=>setMode('saved')}><FolderOpen size={25}/><span><strong>Load Game</strong><small>Saved Games · {saves.length.toLocaleString(getLocale())} bản lưu</small></span></button></nav>
  {mode==='saved'?<main className="start-saved-main"><SavedGames saves={saves} onLoad={onLoad} onImport={onImport} onRename={onRename} onDelete={onDelete} onRefresh={onRefresh} busy={busy}/></main>:<main className="start-main start-new-main">
   <section className="start-club"><div className="eyebrow">SỰ NGHIỆP MỚI / {releaseSeason}</div><h1>Chiếc ghế nóng<br/>đang chờ bạn.</h1><div className="selected-club"><Badge club={selected} size={100}/><div><h2>{selected?.name}</h2><p>{activeLeague?.name} · {players.length.toLocaleString(getLocale())} cầu thủ</p></div></div><div className="start-star"><Portrait player={star} size={230}/><div><span>ĐỘI HÌNH ĐƯỢC CHỌN</span><h3>{star?.name}</h3><p>{star?.photo?'Ảnh từ nguồn công khai':'Avatar minh họa AI'}</p></div></div><div className="start-numbers"><div><b>{db.leagues.filter(l=>l.kind!=='external').length}</b><span>Giải / bảng quốc nội</span></div><div><b>{db.clubs.length.toLocaleString(getLocale())}</b><span>Câu lạc bộ</span></div><div><b>{db.players.length.toLocaleString(getLocale())}</b><span>Cầu thủ</span></div></div><p className="source-note">Chỉ số kỹ năng, tài chính và lịch thi đấu được mô phỏng.</p></section>
   <section className="career-setup"><AssessmentSources/><div className="setup-heading"><h2>Tạo sự nghiệp mới</h2><p className="fine-print">New Game bắt đầu từ giai đoạn chuẩn bị mùa giải, với lịch từng ngày, lời mời giao hữu và phản hồi đàm phán.</p><span>NEW GAME</span></div>
    <div className="roster-release-picker"><label className="field"><span><Database size={17}/>Bản dữ liệu đội hình</span>{rosterReleases.length>0?<select aria-label="Chọn bản dữ liệu đội hình" value={selectedReleaseId||activeRelease.id||rosterReleases[0].id} disabled={locked||!onSelectRelease} onChange={e=>onSelectRelease?.(e.target.value)}>{rosterReleases.map(r=><option key={r.id} value={r.id}>{r.label||r.name||r.id}</option>)}</select>:<strong>{activeRelease.label||'Dữ liệu đang cài trên máy'}</strong>}</label><p>{releaseBusy?<><CircleNotch size={14} className="spin"/>Đang tải bản dữ liệu…</>:<>Mùa {releaseSeason||'chưa rõ'} · Mốc dữ liệu {formatSaveDate(releaseDate)}</>}</p>{activeRelease.notes&&<small>{activeRelease.notes.replace('xem nguồn, rosterNote và meta.provisionalLeagues.', 'xem ghi chú nguồn trong hồ sơ và danh sách giải.').replace('Các tuổi 0 từ nhà cung cấp biểu thị thiếu dữ liệu. ', '')}</small>}<small>Bản dữ liệu này dùng để khởi tạo đội hình cho sự nghiệp mới.</small></div>
    <div className="new-career-fields"><label className="field">Tên huấn luyện viên<input value={manager} onChange={e=>setManager(e.target.value)} maxLength={40} placeholder="Tên của bạn" disabled={locked}/></label><label className="field">Tên bản lưu<input value={saveName} onChange={e=>setSaveName(e.target.value)} maxLength={80} placeholder={`${selected?.shortName||selected?.name} · ${manager.trim()||'HLV'}`} disabled={locked}/></label></div>
    {db.meta.playerReality&&<div className="source-injuries"><label className="check-label"><input type="checkbox" checked={sourceInjuries} disabled={locked} onChange={e=>setSourceInjuries(e.target.checked)}/>Bắt đầu với chấn thương theo bản dữ liệu</label><p className="source-note">Dùng tình trạng được báo tại mốc dữ liệu làm điều kiện khởi đầu. Lịch mùa giải vẫn bắt đầu tháng 8; số tuần hồi phục là ước tính mô phỏng.</p></div>}
    <div className="league-picker">{countries.map(c=><button key={c.code} className={country===c.code?'active':''} disabled={locked} onClick={()=>chooseLeague(db.leagues.find(l=>l.countryCode===c.code&&l.tier===1)?.id)}><span translate="no">{c.code}</span>{c.name}</button>)}</div>
    <label className="field tier-picker">Cấp giải đấu<select aria-label="Chọn cấp giải" value={activeLeague?.id||league} disabled={locked} onChange={e=>chooseLeague(e.target.value)}>{db.leagues.filter(l=>l.countryCode===country&&l.kind!=='external').sort((a,b)=>a.tier-b.tier||a.name.localeCompare(b.name)).map(l=><option key={l.id} value={l.id}>Cấp {l.tier} · {l.name}</option>)}</select></label>{activeLeague?.dataNote&&<p className="source-note">{activeLeague.dataNote}</p>}
    <input className="club-search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Tìm câu lạc bộ…" aria-label="Tìm câu lạc bộ" disabled={locked}/><div className="club-grid">{db.clubs.filter(c=>c.leagueId===activeLeague?.id&&normalize(c.name).includes(normalize(query))).map(c=><button key={c.id} className={selected?.id===c.id?'selected':''} disabled={locked} onClick={()=>setClub(c.id)}><Badge club={c} size={28}/><span>{c.shortName}</span>{selected?.id===c.id&&<Check size={16}/>}</button>)}</div>
    <button className="primary start-button" disabled={locked||!selected} onClick={()=>onNew(selected.id,manager,saveName.trim()||`${selected.shortName||selected.name} · ${manager.trim()||'HLV'}`,{sourceInjuries:!!db.meta.playerReality&&sourceInjuries})}><Play weight="fill" size={18}/>{releaseBusy?'Đang tải đội hình…':`New Game · Dẫn dắt ${selected?.shortName||selected?.name}`}</button>
   </section>
  </main>}
  <footer className="start-footer"><span>TOUCHLINE · FOOTBALL CLUB MANAGER</span><span>ESPN / FotMob / VPF / UEFA · Dữ liệu lưu trên máy</span></footer>
 </div>;
}
