import React,{useState} from 'react';
import {BookOpen,Check,ArrowSquareOut,Strategy} from '@phosphor-icons/react';
import {Modal} from './components.jsx';
import {FORMATION_SLOTS,TACTICAL_PRESETS,DEFAULT_TACTICS,normalizeTactics,TACTIC_OPTIONS,PASSING,TRANSITION} from './tactics.mjs';
export default function TacticsControls({formation,mentality,settings,onFormation,onMentality,onSettings,onPreset,disabled=false,hideFormation=false}){
 const [library,setLibrary]=useState(false),[preview,setPreview]=useState(null);const t=normalizeTactics(settings),active=TACTICAL_PRESETS.find(p=>p.id===t.presetId),chosen=TACTICAL_PRESETS.find(p=>p.id===preview)||active||TACTICAL_PRESETS[0];
 const labels={tempo:'Nhịp độ',width:'Chiều rộng',pressing:'Cường độ pressing',line:'Độ cao hàng thủ'};
 return <><div className="tactical-system"><div className="system-heading"><Strategy size={26}/><div><span>HỆ THỐNG ĐANG DÙNG</span><h2>{active?active.coach+' · '+active.team:'Chiến thuật tùy chỉnh'}</h2><p>{active?active.period+' · '+active.description:'Điều chỉnh cách triển khai bóng, gây áp lực và chuyển trạng thái.'}</p></div><button className="secondary" disabled={disabled} onClick={()=>{setPreview(t.presetId);setLibrary(true);}}><BookOpen size={18}/>Thư viện HLV · 10 mẫu</button></div>
 <div className={"tactic-selectors "+(hideFormation?"without-formation":"")}>{!hideFormation&&<label className="field">Sơ đồ<select aria-label="Sơ đồ chiến thuật" disabled={disabled} value={formation} onChange={e=>onFormation(e.target.value)}>{Object.keys(FORMATION_SLOTS).map(f=><option key={f} value={f} translate="no">{f}</option>)}</select></label>}<label className="field">Tâm thế<select aria-label="Tâm thế chiến thuật" disabled={disabled} value={mentality} onChange={e=>onMentality(e.target.value)}><option value="balanced">Cân bằng</option><option value="attacking">Tấn công</option><option value="defensive">Phòng ngự</option></select></label><label className="field">Chuyền bóng<select disabled={disabled} value={t.passing} onChange={e=>onSettings({...t,passing:e.target.value,presetId:'custom'})}>{Object.entries(PASSING).map(([k,v])=><option value={k} key={k}>{v}</option>)}</select></label><label className="field">Khi chuyển trạng thái<select disabled={disabled} value={t.transition} onChange={e=>onSettings({...t,transition:e.target.value,presetId:'custom'})}>{Object.entries(TRANSITION).map(([k,v])=><option value={k} key={k}>{v}</option>)}</select></label></div>
 <div className="tactic-sliders">{Object.entries(TACTIC_OPTIONS).map(([k,choices])=><label key={k}><span>{labels[k]}<b>{choices[t[k]-1]}</b></span><input aria-label={labels[k]} type="range" min="1" max="5" step="1" disabled={disabled} value={t[k]} onChange={e=>onSettings({...t,[k]:Number(e.target.value),presetId:'custom'})}/></label>)}</div>
 <p className="fine-print">Pressing và nhịp độ cao tạo áp lực nhưng tốn thể lực. Hàng thủ cao dễ bị phản công; chuyền ngắn cần kỹ thuật. Các tham số ảnh hưởng mô phỏng, không bảo đảm chiến thắng.</p></div>
 {library&&<Modal title="Thư viện chiến thuật HLV" wide onClose={()=>setLibrary(false)}><div className="tactic-library"><div className="preset-list">{TACTICAL_PRESETS.map(p=><button key={p.id} className={chosen.id===p.id?'selected':''} onClick={()=>setPreview(p.id)}><strong>{p.coach}</strong><span>{p.team} · {p.period}</span><small>{p.formation}{active?.id===p.id?' · Đang dùng':''}</small></button>)}</div><article className="preset-detail"><span className="eyebrow">{chosen.team} / {chosen.period}</span><h2>{chosen.coach}</h2><div className="preset-formation">{chosen.formation}</div><p>{chosen.description}</p><h3>Nhân sự phù hợp</h3><p>{chosen.strength}</p><h3>Điểm cần bù đắp</h3><p>{chosen.risk}</p><div className="preset-tags">{['pressing','line','tempo'].map(k=><span key={k} className="tag">{labels[k]}: {TACTIC_OPTIONS[k][chosen.settings[k]-1]}</span>)}</div><a href={chosen.source} target="_blank" rel="noreferrer">Phân tích nguồn <ArrowSquareOut size={14}/></a><p className="fine-print">Mẫu mô phỏng lấy cảm hứng từ giai đoạn ghi trên thẻ. Đây không phải khẳng định HLV vẫn dẫn dắt đội đó, hoặc tái hiện từng chỉ đạo ngoài đời. Tham số và đánh giá phù hợp do game thiết kế.</p><button className="primary" onClick={()=>{if(onPreset(chosen.id)!==false)setLibrary(false);}}><Check size={18}/>Áp dụng {chosen.coach}</button><p className="fine-print">Áp dụng sắp lại 11 vị trí bằng các cầu thủ đang có trên sân. Nếu bật hai pha, mẫu cập nhật sơ đồ có bóng; sơ đồ không bóng được giữ. Chọn “Xếp đội hình tốt nhất” ở trước trận để tự chọn lại nhân sự.</p></article></div></Modal>}</>;
}
