import React,{useEffect,useRef,useState} from 'react';
import {DotsSixVertical,Check,ArrowsLeftRight,MagnifyingGlass,X,ArrowSquareOut,UserMinus} from '@phosphor-icons/react';
import {Pitch,Portrait,Rating,Meter,PlayerPosition} from './components.jsx';
import {FORMATION_SLOTS,roleFit,fitLabel,FOOT} from './tactics.mjs';
import {overall,available,currentFixture} from './engine.mjs';
import {registered} from './registration.mjs';
import {competitionSuspension} from './discipline.mjs';
import {positionCode} from './playerPositions.mjs';
import {matchdayRule,liveMatchdayRule,matchSubLimit} from './matchday.mjs';
import {defaultPlayerRole,playerRoleDefinition} from './playerRoles.mjs';
import {pitchPoint} from './tacticalPositionInput.mjs';
import TacticalRoleEditor from './TacticalRoleEditor.jsx';
import {ReadinessBadge} from './PhysicalReadiness.jsx';
import {matchCondition} from './playerPhysical.mjs';
import {number} from './locale.mjs';
import './matchday.css';
import './tactical-roles.css';

export default function TacticalBoard({g,formation,lineup,players,onAssign,onAssignBench,onRemoveBench,onProfile,live=null,side=0,onInteract,phaseLabel,positions,roleIds,phase='inPossession',dualEnabled=false,onStartPositionEditing,onPosition,onRole,onResetPositions,competitionId=currentFixture(g)?.leagueId}){
 const [slot,setSlot]=useState(null),[benchSlot,setBenchSlot]=useState(null),[chosen,setChosen]=useState(null),[query,setQuery]=useState(''),[drag,setDrag]=useState(null),[notice,setNotice]=useState('');
 const [positionMode,setEditPositions]=useState(false),[positionIndex,setPositionIndex]=useState(5),[positionPreview,setPositionPreview]=useState(null),editPositions=positionMode&&dualEnabled;
 const gesture=useRef(null),suppress=useRef(0),root=useRef(null),roles=positions||FORMATION_SLOTS[formation],bench=live?live.bench[side]:(g.bench||[]),rule=live?liveMatchdayRule(g,live):matchdayRule(g,competitionId);
 const assignedRoles=roles.map(([p],i)=>roleIds?.[i]||defaultPlayerRole(p,phase));
 const eligible=p=>!!p&&(live?!live.completed&&!live.red.includes(p.id)&&!live.off.includes(p.id)&&!live.injured.includes(p.id)&&(lineup.includes(p.id)||bench.includes(p.id)):available(p)&&registered(g,p,competitionId));
 const cancel=()=>{gesture.current=null;setDrag(null);setPositionPreview(null);setChosen(null);setSlot(null);setBenchSlot(null);};
 useEffect(()=>{if(!dualEnabled){cancel();setEditPositions(false);}},[dualEnabled]);
 const changePosition=(index,patch)=>{const ok=onPosition?.(index,patch);if(ok!==false){setPositionIndex(index);setNotice('Đã cập nhật vị trí trên sân.');}return ok;};
 const assign=(index,id)=>{const ok=onAssign(index,id);if(ok!==false){setNotice(`${g.players[id].name} → ${positionCode(roles[index][0])}.`);cancel();}};
 const assignBench=(index,id)=>{if(live){const outgoing=lineup.indexOf(id),incoming=bench[index];if(outgoing>=0&&incoming)assign(outgoing,incoming);else setNotice('Trong trận, kéo cầu thủ dự bị vào sân để thay người.');return;}const ok=onAssignBench?.(index,id);if(ok!==false){setNotice(`${g.players[id].name} đã được xếp vào danh sách dự bị.`);cancel();}};
 const targetAt=(x,y)=>{const el=document.elementFromPoint(x,y)?.closest('[data-drop-slot],[data-bench-slot],[data-outside-bench]');if(!el||!root.current?.contains(el))return null;return el.hasAttribute('data-drop-slot')?{kind:'starter',index:Number(el.dataset.dropSlot)}:el.hasAttribute('data-bench-slot')?{kind:'bench',index:Number(el.dataset.benchSlot)}:{kind:'outside'};};
 const drop=(target,id)=>{if(target?.kind==='starter')assign(target.index,id);else if(target?.kind==='bench')assignBench(target.index,id);else if(target?.kind==='outside'&&!live&&bench.includes(id)){if(onRemoveBench?.(id)!==false){setNotice(`${g.players[id].name} đã được đưa ra ngoài danh sách trận.`);cancel();}}else setNotice('Đã hủy kéo thả. Thả vào vị trí trên sân hoặc một ô dự bị.');};
 const start=(e,id)=>{if(e.button!==0||!eligible(g.players[id]))return;onInteract?.();e.currentTarget.setPointerCapture(e.pointerId);gesture.current={id,x:e.clientX,y:e.clientY,pointer:e.pointerId,active:false};};
 const move=e=>{const a=gesture.current;if(!a||a.pointer!==e.pointerId)return;if(Math.hypot(e.clientX-a.x,e.clientY-a.y)>6)a.active=true;if(!a.active)return;e.preventDefault();if(a.kind==='position'){const point=pitchPoint(e.clientX,e.clientY,a.rect);if(point)setPositionPreview({index:a.index,...point});}else setDrag({id:a.id,x:e.clientX,y:e.clientY,target:targetAt(e.clientX,e.clientY)});};
 const end=e=>{const a=gesture.current;if(!a||a.pointer!==e.pointerId)return;gesture.current=null;setDrag(null);setPositionPreview(null);if(a.active){suppress.current=performance.now()+350;if(a.kind==='position'){const inside=e.clientX>=a.rect.left&&e.clientX<=a.rect.right&&e.clientY>=a.rect.top&&e.clientY<=a.rect.bottom;const point=inside&&pitchPoint(e.clientX,e.clientY,a.rect);if(point)changePosition(a.index,point);else setNotice('Đã hủy di chuyển vị trí.');}else drop(targetAt(e.clientX,e.clientY),a.id);}};
 const bindings=id=>id&&eligible(g.players[id])?{onPointerDown:e=>start(e,id),style:{touchAction:'none'},'data-drag-player':id}:{};
 const positionBindings=(index,p)=>({style:{touchAction:'none'},onPointerDown:e=>{if(e.button!==0||roles[index][0]==='GK'||live&&(live.completed||!eligible(p)))return;onInteract?.();const rect=e.currentTarget.closest('.tactics-pitch').getBoundingClientRect();e.currentTarget.setPointerCapture(e.pointerId);gesture.current={kind:'position',index,x:e.clientX,y:e.clientY,pointer:e.pointerId,active:false,rect};setPositionIndex(index);}});
 const pick=id=>{if(slot!==null)assign(slot,id);else if(benchSlot!==null)assignBench(benchSlot,id);else{setChosen(chosen===id?null:id);setNotice('Đã chọn '+g.players[id].name+'. Chọn vị trí trên sân hoặc ô dự bị. Escape để hủy.');}};
 const selectSeat=i=>{if(chosen)assignBench(i,chosen);else{setSlot(null);setBenchSlot(benchSlot===i?null:i);setNotice(`Chọn cầu thủ cho ô dự bị ${i+1}.`);}};
 const normalize=s=>s.toLocaleLowerCase('vi').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replaceAll('đ','d');
 const sorted=[...players].filter(p=>normalize(p.name).includes(normalize(query))).sort((a,b)=>slot!==null?roleFit(b,roles[slot][0])*100+overall(b)/10-roleFit(a,roles[slot][0])*100-overall(a)/10:overall(b)-overall(a));
 const row=p=>{const out=live?.off.includes(p.id),red=live?.red.includes(p.id),injured=live?.injured.includes(p.id)||p.injury>0,enabled=eligible(p);return <div key={p.id} className={'tactical-person '+(lineup.includes(p.id)?'in-lineup ':'')+(chosen===p.id?'picked':'')}><button type="button" className="drag-handle" aria-label={'Kéo '+p.name} title="Kéo vào sân hoặc dự bị" disabled={!enabled} {...bindings(p.id)} onClick={()=>pick(p.id)}><DotsSixVertical/></button><Portrait player={p} size={34}/><div className="tactical-person-info">{onProfile?<button className="player-text-button" onClick={()=>onProfile(p.id)}>{p.name}</button>:<strong>{p.name}</strong>}<small>Sở trường: <PlayerPosition player={p} compact/> · {p.preferredFoot==='both'?'Thuận hai chân':p.preferredFoot&&p.preferredFoot!=='unknown'?'Chân '+FOOT[p.preferredFoot].toLowerCase():'Chân thuận chưa rõ'}</small><div className="tactical-condition"><Meter value={matchCondition(g,p,live)}/><span>{number(matchCondition(g,p,live))}%</span><span>{red?'Thẻ đỏ':out?'Đã ra':injured?'Chấn thương':!live&&(p.suspension>0||competitionSuspension(g,p,competitionId)>0)?'Treo giò':lineup.includes(p.id)?'Trên sân':enabled?'Ngoài danh sách':'Chưa đủ điều kiện'}</span></div>{!red&&!out&&<ReadinessBadge g={g} p={p} live={live}/>} {slot!==null&&<small className={roleFit(p,roles[slot][0])<.8?'amber':'lime'}>{fitLabel(p,roles[slot][0])}</small>}</div><Rating player={p} small/><button className="small-button choose-player" aria-label={'Xếp '+p.name} disabled={!enabled} onClick={()=>pick(p.id)}>{chosen===p.id?<Check size={16}/>:slot!==null||benchSlot!==null?'Xếp':'Chọn'}</button></div>;};
 return <div ref={root} className={'tactical-board matchday-board '+(drag?'is-dragging ':'')+(editPositions?'editing-positions':'')} onPointerMove={move} onPointerUp={end} onPointerCancel={cancel} onKeyDown={e=>{if(e.key==='Escape'&&(gesture.current||chosen||slot!==null||benchSlot!==null)){cancel();e.stopPropagation();}}} onClickCapture={e=>{if(performance.now()<suppress.current){e.preventDefault();e.stopPropagation();}}}>
  <div className="tactical-board-pitch"><div className="matchday-group-heading"><strong>{phaseLabel||"Đội hình xuất phát"}</strong><span>{lineup.filter(Boolean).length}/11</span></div>
   {onPosition&&<div className="segmented tactical-board-mode" aria-label="Cách chỉnh chiến thuật"><button aria-pressed={!editPositions} className={!editPositions?'active':''} onClick={()=>{cancel();setEditPositions(false);}}>Đổi cầu thủ</button><button aria-pressed={editPositions} className={editPositions?'active':''} onClick={()=>{cancel();if(!dualEnabled&&onStartPositionEditing?.()===false)return;setEditPositions(true);}}>Chỉnh vị trí & role</button></div>}
   {editPositions&&<p className="position-edit-help">Kéo áo đến khoảng trống để đổi vị trí. Bấm áo để chọn role hoặc dùng bảng chọn vị trí.</p>}
   <Pitch g={g} formation={formation} positions={roles} roleLabels={editPositions?assignedRoles.map(id=>playerRoleDefinition(id)?.label):null} positionPreview={positionPreview} lineup={lineup} selected={editPositions?positionIndex:slot} dropTarget={drag?.target?.kind==='starter'?drag.target.index:null} dragBindings={bindings} slotBindings={editPositions?positionBindings:null} live={live} onSelect={i=>{if(editPositions){setPositionIndex(i);return;}if(benchSlot!==null&&lineup[i]){assignBench(benchSlot,lineup[i]);return;}setBenchSlot(null);if(chosen)assign(i,chosen);else setSlot(slot===i?null:i);}}/>
   <p className="drag-help"><ArrowsLeftRight size={18}/>{phaseLabel?`Đang chỉnh ${phaseLabel.toLowerCase()}. Đổi chỗ cầu thủ trong pha này; thay người ở cả hai pha.`:live?'Kéo dự bị vào sân hoặc kéo cầu thủ trên sân xuống ô dự bị để thay người.':'Kéo thả giữa sân, dự bị và ngoài danh sách để chọn đội hình trận đấu.'}</p>
   <p className="fine-print">Bàn phím: chọn cầu thủ rồi bấm vị trí trên sân hoặc ô dự bị; hoặc chọn ô dự bị rồi bấm cầu thủ trên sân. Escape để hủy.</p>
   {live&&rule.subWindows!=null&&<p className="fine-print">Đã dùng {live.subWindows?.[side]||0}/{rule.subWindows+(live.extraTime&&rule.extraTimeSub?1:0)} đợt thay. Thay nhiều người khi đang dừng ở cùng một phút tính một đợt; nghỉ giữa hiệp không mất đợt.</p>}{live&&<p className="tactics-note">Cầu thủ đã thay ra hoặc nhận thẻ đỏ không thể trở lại. Đổi vị trí giữa các cầu thủ trên sân không mất lượt thay.</p>}
  </div>
  <div className="matchday-personnel">
   {editPositions&&<TacticalRoleEditor player={g.players[lineup[positionIndex]]} index={positionIndex} position={roles[positionIndex][0]} roleId={assignedRoles[positionIndex]} phase={phase} dualEnabled={dualEnabled} disabled={!!live&&(live.completed||!eligible(g.players[lineup[positionIndex]]))} onPosition={changePosition} onRole={(index,id)=>{if(onRole?.(index,id)!==false)setNotice('Đã cập nhật vai trò cầu thủ.');}} onReset={onResetPositions}/>}
   <section className="matchday-bench" aria-label="Danh sách dự bị trận đấu"><div className="matchday-group-heading"><strong>Ghế dự bị</strong><span>{bench.length}/{rule.maxBench}</span></div><div className="matchday-bench-grid">{Array.from({length:Math.max(rule.maxBench,bench.length)},(_,i)=>{const p=g.players[bench[i]],targeted=drag?.target?.kind==='bench'&&drag.target.index===i;return <div key={i} data-bench-slot={i} className={'matchday-bench-seat '+(targeted||benchSlot===i?'is-target ':'')+(chosen===p?.id?'picked':'')}>{p?<><button className="drag-handle" aria-label={'Kéo '+p.name+' từ dự bị'} {...bindings(p.id)} onClick={()=>pick(p.id)} disabled={!eligible(p)}><DotsSixVertical size={16}/></button><Portrait player={p} size={30}/><div><button className="matchday-bench-name" onClick={()=>chosen?assignBench(i,chosen):pick(p.id)} disabled={!eligible(p)}>{p.name}</button><small><PlayerPosition player={p} compact/> · {number(matchCondition(g,p,live))}%</small>{!live?.red.includes(p.id)&&!live?.off.includes(p.id)&&<ReadinessBadge g={g} p={p} live={live}/>}</div><button className="matchday-seat-number" aria-label={'Xếp vào ô dự bị '+(i+1)} onClick={()=>selectSeat(i)} disabled={!!live&&!chosen}>D{i+1}</button>{!live&&<button className="matchday-remove" aria-label={'Bỏ '+p.name+' khỏi dự bị'} title="Đưa ra ngoài danh sách" onClick={()=>onRemoveBench?.(p.id)}><UserMinus size={13}/></button>}</>:<button className="matchday-empty-seat" aria-label={'Xếp vào ô dự bị '+(i+1)} onClick={()=>selectSeat(i)} disabled={!!live}><span>D{i+1}</span><small>{benchSlot===i?'Chọn cầu thủ…':'Thả cầu thủ vào đây'}</small></button>}</div>;})}</div></section>
   <div className="matchday-rule"><p><strong>{rule.label}</strong> · Tối đa {rule.maxBench} dự bị · {live?`${live.subs[side]}/${matchSubLimit(live)}`:rule.maxSubs} cầu thủ thay {rule.subWindows?`trong ${rule.subWindows} đợt`:live&&!live.matchdayRules?'không giới hạn đợt':'theo thỏa thuận'}{rule.extraTimeSub?' · +1 khi đá hiệp phụ':''}.</p><small>{rule.verified?'Nguồn điều lệ':'Thiết lập mô phỏng'}: <a href={rule.sourceUrl} target="_blank" rel="noreferrer">{rule.sourceLabel} <ArrowSquareOut size={10}/></a>{rule.sourceSeason?' · '+rule.sourceSeason:''}. {rule.notes}</small></div>
  <section className="panel tactical-people"><header className="panel-head"><div><h2>{slot!==null?`Xếp ${positionCode(roles[slot][0])} · Vị trí ${slot+1}`:benchSlot!==null?`Chọn dự bị ${benchSlot+1}`:live?'Nhân sự trận đấu':'Ngoài danh sách trận'}</h2><p>{chosen?g.players[chosen].name+' đang được chọn':'Kéo bằng biểu tượng ⋮⋮ hoặc bấm Chọn'}</p></div>{(chosen||slot!==null||benchSlot!==null)&&<button className="icon-button" aria-label="Hủy chọn cầu thủ" onClick={cancel}><X/></button>}</header><div className="search padded-search"><MagnifyingGlass size={18}/><input aria-label="Tìm cầu thủ chiến thuật" placeholder="Tìm cầu thủ…" value={query} onChange={e=>setQuery(e.target.value)}/></div><div className="tactical-roster">{live&&<><div className="matchday-roster-heading">Đang trên sân <span>{lineup.filter(Boolean).length}</span></div>{sorted.filter(p=>lineup.includes(p.id)).map(row)}</>}<div className={'matchday-outside '+(drag?.target?.kind==='outside'?'is-target':'')} {...(!live?{'data-outside-bench':true}:{})}><div className="matchday-roster-heading">{live?'Đã rời sân':'Ngoài danh sách trận'}<span>{players.filter(p=>!lineup.includes(p.id)&&!bench.includes(p.id)).length}</span></div>{!live&&<p className="matchday-outside-help">Kéo cầu thủ dự bị vào vùng này để bỏ khỏi danh sách.</p>}{sorted.filter(p=>!lineup.includes(p.id)&&!bench.includes(p.id)).map(row)}{!sorted.some(p=>!lineup.includes(p.id)&&!bench.includes(p.id))&&<p className="fine-print matchday-empty-roster">Không có cầu thủ trong nhóm này.</p>}</div></div></section>
  </div>
  <p className="board-announcement" role="status" aria-live="polite">{notice||'Sẵn sàng xếp đội hình và dự bị.'}</p>{drag&&<div className="drag-player-ghost" style={{left:drag.x+14,top:drag.y+14}}><Portrait player={g.players[drag.id]} size={30}/><strong>{g.players[drag.id].name}</strong></div>}
 </div>;
}
