import React,{useState} from 'react';
import {Lightning} from '@phosphor-icons/react';
import {PageTitle} from './components.jsx';
import TacticalBoard from './TacticalBoard.jsx';
import TacticsControls from './TacticsControls.jsx';
import PhaseTacticsPanel from './PhaseTacticsPanel.jsx';
import {clubPlayers,autoPhaseLineup,setFormation,applyTacticPreset,available,currentFixture,overall,enablePhaseTactics,setPhaseFormation,assignPhaseSlot} from './engine.mjs';
import {registered} from './registration.mjs';
import {normalizeTactics,TACTICAL_PHASES,phaseShape,phaseLineup} from './tactics.mjs';
import {matchdayRule,repairBench,assignBenchSlot,removeFromBench,setMatchdayRule} from './matchday.mjs';
export default function TacticsPage({g,mutate,openPlayer,competitionId=currentFixture(g)?.leagueId}){
 const [phase,setPhase]=useState('inPossession'),shape=phaseShape(g.phaseTactics,phase,g.formation),lineup=phaseLineup(g.lineup,g.phaseTactics,phase,g.formation);
 const options=x=>({competitionId,eligible:p=>available(p)&&registered(x,p,competitionId),rank:overall}),rule=matchdayRule(g,competitionId);
 return <><PageTitle eyebrow="BAN HUẤN LUYỆN" title="Phòng chiến thuật" description="Chọn hệ thống, đội hình xuất phát và danh sách dự bị cho trận kế tiếp." action={<button className="secondary" onClick={()=>mutate(x=>{x.lineup=autoPhaseLineup(x,competitionId);repairBench(x,{...options(x),fill:true});},'Đã chọn đội hình và bổ sung dự bị theo năng lực.')}><Lightning size={18}/>Xếp đội hình tốt nhất</button>}/><TacticsControls hideFormation={g.phaseTactics?.enabled} formation={g.formation} mentality={g.mentality} settings={g.tactics} onFormation={f=>mutate(x=>setFormation(x,f))} onMentality={v=>mutate(x=>{x.mentality=v;x.tactics={...normalizeTactics(x.tactics),presetId:'custom'};})} onSettings={s=>mutate(x=>{x.tactics=s;})} onPreset={id=>mutate(x=>applyTacticPreset(x,id),'Đã áp dụng hệ thống chiến thuật.')}/><PhaseTacticsPanel g={g} config={g.phaseTactics} lineup={g.lineup} formation={g.formation} phase={phase} onPhase={setPhase} onEnable={enabled=>mutate(x=>enablePhaseTactics(x,enabled))} onFormation={(p,f)=>mutate(x=>setPhaseFormation(x,p,f))}/>{!rule.verified&&<details className="matchday-rule-controls"><summary>Điều lệ mô phỏng · {rule.label}</summary><p>{rule.notes} Giới hạn dưới đây áp dụng cho các trận chưa bắt đầu.</p><label>Số dự bị<select aria-label="Giới hạn dự bị mô phỏng" value={rule.maxBench} onChange={e=>mutate(x=>setMatchdayRule(x,rule.id,{maxBench:Number(e.target.value),maxSubs:Math.min(rule.maxSubs,Number(e.target.value))}),'Đã cập nhật giới hạn dự bị.')} >{Array.from({length:13},(_,i)=>i+3).map(n=><option key={n} value={n}>{n}</option>)}</select></label><label>Số cầu thủ thay<select aria-label="Giới hạn cầu thủ thay mô phỏng" value={rule.maxSubs} onChange={e=>mutate(x=>setMatchdayRule(x,rule.id,{maxSubs:Number(e.target.value)}),'Đã cập nhật giới hạn thay người.')}>{Array.from({length:rule.maxBench},(_,i)=>i+1).map(n=><option key={n} value={n}>{n}</option>)}</select></label></details>}<TacticalBoard key={phase+shape.formation+!!g.phaseTactics?.enabled} phaseLabel={g.phaseTactics?.enabled?TACTICAL_PHASES[phase]:null} g={g} competitionId={competitionId} formation={shape.formation} lineup={lineup} players={clubPlayers(g,g.clubId)} onProfile={openPlayer} onAssign={(i,id)=>mutate(x=>assignPhaseSlot(x,phase,i,id,competitionId),'Đã cập nhật đội hình.')} onAssignBench={(i,id)=>mutate(x=>assignBenchSlot(x,i,id,options(x)),'Đã cập nhật danh sách dự bị.')} onRemoveBench={id=>mutate(x=>removeFromBench(x,id),'Đã đưa cầu thủ ra ngoài danh sách trận.')}/></>;
}
